### ISSUE TITLE
Check slide.css footer CSS

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/intro-data-vis-excel#2]
Look like the slide numbers are bigger than they should be.

**Comment by lizdumont** [comment]
@datapolitan do you mind taking this? Or, showing me how to troubleshoot on our call today?

**Comment by datapolitan** [comment]
It's not an issue. I should've looked before I opened the issue, but the CSS is good. 

```css
.remark-slide-number {
  font-size:0.75em;
  bottom:5px;
  right:10px;
}
```
